/**************************************************************************/
/*  jellygrid_swarm_sim.hpp                                               */
/**************************************************************************/
/* Pure jellyfish swarm simulation logic — no Godot, no api.hpp.         */
/* Included by both:                                                      */
/*   - demo/abyssal_vr/sandbox/jellygrid_swarm.cpp (RISC-V guest)        */
/*   - tests/test_jellygrid_swarm.h (Godot test runner, ASAN)            */
/**************************************************************************/

#pragma once
#include <array>
#include <cmath>
#include <cstdint>

namespace JellygridSwarm {

static constexpr int   MAX_JELLYFISH   = 512;
static constexpr float BLOOM_TTL       = 30.0f;
static constexpr float PREDATOR_RADIUS = 2.5f;
static constexpr float CURRENT_DECAY   = 0.12f;
static constexpr float BASE_SPEED      = 1.4f;
static constexpr float RIP_STRENGTH    = 3.8f;
static constexpr int   GRID            = 8;
static constexpr float SIM_BOUND       = 15.0f;
static constexpr float CELL            = SIM_BOUND * 2.0f / GRID;
static constexpr int   MAX_PREDATORS   = 8;

struct Jellyfish {
	bool  alive = false;
	float ttl   = BLOOM_TTL;
	float x = 0.0f, y = 0.0f, z = 0.0f;
	float phase = 0.0f;
};

struct Vec2 { float x, z; };

struct Predator {
	bool  active = false;
	float x = 0.0f, y = 0.0f, z = 0.0f;
};

struct State {
	std::array<Jellyfish, MAX_JELLYFISH> fish{};
	std::array<Vec2, GRID * GRID>        flow{};
	std::array<Predator, MAX_PREDATORS>  predators{};
	int   alive_count   = 0;
	float power_tick_kw = 0.0f;
};

inline int grid_idx(float x, float z) {
	int gx = (int)((x + SIM_BOUND) / CELL);
	int gz = (int)((z + SIM_BOUND) / CELL);
	gx = gx < 0 ? 0 : (gx >= GRID ? GRID - 1 : gx);
	gz = gz < 0 ? 0 : (gz >= GRID ? GRID - 1 : gz);
	return gz * GRID + gx;
}

// Returns kW contributed this tick (sum of jellyfish_reached_node calls).
inline void tick(State &s, float delta) {
	s.power_tick_kw = 0.0f;
	int alive = 0;

	for (int i = 0; i < MAX_JELLYFISH; ++i) {
		auto &f = s.fish[i];
		if (!f.alive) continue;

		f.ttl   -= delta;
		f.phase += delta * 6.7f;
		if (f.phase > 6.2832f) f.phase -= 6.2832f;

		if (f.ttl <= 0.0f) { f.alive = false; continue; }

		auto &flow = s.flow[grid_idx(f.x, f.z)];
		f.x += (flow.x + BASE_SPEED * 0.3f) * delta;
		f.z += (flow.z + BASE_SPEED * 0.3f) * delta;

		for (auto &p : s.predators) {
			if (!p.active) continue;
			float dx = f.x - p.x, dz = f.z - p.z;
			float dist = std::sqrt(dx * dx + dz * dz) + 0.001f;
			if (dist < PREDATOR_RADIUS) {
				float flee = (PREDATOR_RADIUS - dist) / PREDATOR_RADIUS * 4.0f;
				f.x += (dx / dist) * flee * delta;
				f.z += (dz / dist) * flee * delta;
			}
		}
		++alive;
	}

	float keep = 1.0f - CURRENT_DECAY * delta;
	for (auto &cell : s.flow) { cell.x *= keep; cell.z *= keep; }

	s.alive_count = alive;
}

inline void spawn(State &s, int id) {
	if (id < 0 || id >= MAX_JELLYFISH) return;
	s.fish[id] = {};
	s.fish[id].alive = true;
	s.fish[id].ttl   = BLOOM_TTL;
	s.fish[id].phase = (float)(id & 63) / 64.0f * 6.2832f;
	++s.alive_count;
}

// Returns kW generated by this arrival.
inline float jellyfish_reached_node(State &s, int id) {
	if (id < 0 || id >= MAX_JELLYFISH || !s.fish[id].alive) return 0.0f;
	float sync = 0.5f + 0.5f * std::sin(s.fish[id].phase);
	float kw   = 0.1f * (1.0f + sync);
	s.power_tick_kw += kw;
	s.fish[id].alive = false;
	--s.alive_count;
	return kw;
}

inline void apply_current(State &s, float x, float z, float vx, float vz) {
	auto &cell = s.flow[grid_idx(x, z)];
	cell.x += vx * 0.6f;
	cell.z += vz * 0.6f;
}

inline void inject_rip_current(State &s, float origin_x, float origin_z) {
	for (int gi = 0; gi < GRID; ++gi) {
		for (int gj = 0; gj < GRID; ++gj) {
			float cx = -SIM_BOUND + (gi + 0.5f) * CELL;
			float cz = -SIM_BOUND + (gj + 0.5f) * CELL;
			float dx = cx - origin_x, dz = cz - origin_z;
			float dist = std::sqrt(dx * dx + dz * dz) + 0.001f;
			float mag  = RIP_STRENGTH / (1.0f + dist * dist * 0.2f);
			s.flow[gj * GRID + gi].x += (dx / dist) * mag;
			s.flow[gj * GRID + gi].z += (dz / dist) * mag;
		}
	}
}

inline void add_predator(State &s, float x, float y, float z) {
	for (auto &p : s.predators)
		if (!p.active) { p = {true, x, y, z}; return; }
}

} // namespace JellygridSwarm
